authlib/authlib

authlib/client/oauth2.py

`TypeError` fix when using no `refresh_token_params`.

---

authlib/specs/rfc6749/grants/refresh_token.py

Servers may bind tokens to client IDs to reduce chance of token abuse [[1]](https://tools.ietf.org/html/rfc6819#section-5.1.5.8), but `RefreshTokenGrant` does not allow for this functionality.
In `validate_token_request`, the client is validated before the user function `authenticate_refresh_token` is called, but the client isn't saved as an instance variable until after that function call.  
This change allows `authenticate_refresh_token` to access the client with `self.request.client` to allow this functionality while not changing the API of `authenticate_refresh_token`
(If no, …

Allow RefreshTokenGrant to validate client / token relationship

---

authlib/specs/rfc6749/errors.py
tests/flask/test_oauth2/test_oauth2_server.py

Make MissingAuthorizationError and UnsupportedTokenTypeError return
status code 401.
Debatable, it is an API change, but clients will probably catch all 4xx errors.
---

Return 401 on Authorization header errors

---

authlib/client/oauth2_session.py

enable client-side ssl certificates for oauth2 session

---

docs/jose/jwt.rst

Changed `equals` to `returns` as it's more clear from a programmer POV what it means. Also fixed some typos
Docs
---

Some doc fixes for jwt

---

authlib/oauth2/client.py

For example, this allows use with some custom grant type with
username/password like Auth0's "Realm Support":
https://auth0.com/docs/api-auth/tutorials/password-grant#realm-support
Allow additional option for users.
---

Support Custom Grant Type when fetching tokens with Username/Password

---

.codeclimate.yml
.travis.yml
authlib/integrations/starlette_client/__init__.py
authlib/integrations/starlette_client/oauth_registry.py
authlib/integrations/starlette_client/remote_app.py
authlib/starlette/client/__init__.py
authlib/starlette/client/oauth.py
docs/client/starlette.rst
tests/starlette/test_oauth_client.py
tox.ini

This commit adds a new Starlette client along with documentation and
tests. The Starlette client is suitable for use with frameworks that
build on top of Starlette such as FastAPI and Bocadillo.
This implements #148.
---

Add Starlette client (#148)

---

docs/client/frameworks.rst

OAuth2Token "expires_at" should be integer as it is epoch type (number of seconds since 1970)
documentation update
---

OAuth2Token expires_at should be integer

---

authlib/integrations/httpx_client/assertion_client.py
authlib/integrations/httpx_client/oauth1_client.py
authlib/integrations/httpx_client/oauth2_client.py

In the `0.8.0` release of httpx the sync support was dropped and some classes have been removed:
`AsyncClient, AsyncRequest, AsyncResponse` and moved to `Client, Request, Response`. Here some more information: [Commit](https://github.com/encode/httpx/commit/00e150f6a5f8d295faeadc34cfe53de254b3f264) / [Discussion](https://github.com/encode/httpx/issues/522)
This PR closes #171 and fixes:
- `AsyncClient`  is renamed to `Client` 
- `AsyncRequest` is renamed to `Request`
- `AsyncResponse` is renamed to `Response`
- `BaseMiddleware` is renamed to `Middleware`  
---
---

Httpx sync drop

---

authlib/common/errors.py

This fixes the issue when api request is made using wrong token multiple times.
WWW-Authenticate header is added on each response.
> on README.
---

Do not mutate default_json_header constant

---

authlib/oauth2/auth.py

If the Content-Length header has already been populated when the encoding methods
update the body content, the Content-Length needs to be updated to include the new text.
Closes #190 
---

Update Content-Length header if present when body size changes

---

docs/flask/1/authorization-server.rst

In the example to define the TimestampNonce there is referring to the `OAuth1TokenCredentialMixin` and should be `OAuth1TimestampNonceMixin`
> on README.
---

Fixing the name of the Nonce model

---

docs/flask/1/authorization-server.rst

The name of the `create_temporary_credential_response()` is wrong, there is missing and `s` in the `credential-s-` section.
> on README.
- [x ] Other, please describe: Typo
- [x ] No
---
- [x ] You consent that the copyright of your pull request source code belongs to Authlib's author.

Fixing Typo

---

authlib/integrations/httpx_client/oauth2_client.py

Removes url parameters and/or form parameters while checking for refreshing token.  Closes Bug #201
> on README.
---

Removing the extra args while refreshing token

---

authlib/oauth2/rfc6749/wrappers.py

**Description**
Some providers provide endless access tokens, therefore, if you specify None for expires_at or expires_in - a token initialization error occurs.
For example, such services are GitHub and Gitlab. Moreover, in the case of the Gitlab, the token for updating is returned, but without expires_at (long-live bug and it won't be fixed, probably).
**Links**:
* Gitlab token: https://stackoverflow.com/questions/39264452/gitlab-oauth-access-token-validity
* GitHub token: https://stackoverflow.com/questions/26902600/whats-the-lifetime-of-github-oauth-api-access-token

🐛 fix for "expires_at" / "expires_in" param when "None" is specified

---

authlib/integrations/httpx_client/oauth1_client.py
authlib/integrations/httpx_client/oauth2_client.py
tests/py3/test_httpx_client/test_async_assertion_client.py
tests/py3/test_httpx_client/test_async_oauth1_client.py
tests/py3/test_httpx_client/test_async_oauth2_client.py
tests/py3/test_starlette_client/test_oauth_client.py
tests/py3/test_starlette_client/test_user_mixin.py
tests/py3/utils.py

A couple of changes here to start to make sure that authlib only imports from the httpx public API...
* Import `Request`/`Response` from the top-level API.
* Switch to using `httpx.AsyncClient(app=...)` instead of relying on the undocumented dispatch API.
I still need to look at the usage of the ContentStreams API and figure out if https://github.com/encode/httpx/pull/932/files is the right approach, or if there's already sufficient public API here, and the auth flow just need re-jigging.
---
---

Import from the `httpx` public API.

---

authlib/integrations/httpx_client/oauth1_client.py
authlib/integrations/httpx_client/oauth2_client.py
authlib/integrations/httpx_client/utils.py
tests/py3/test_httpx_client/test_async_oauth1_client.py

Rejig the auth flow slightly, so as to not rely on `httpx`'s private `ContentStreams`.
After this fix I believe authlib should be compatible with `httpx` 0.12, the upcoming 0.13, and the planned 1.x series.
---

Drop usage of private httpx ContentStreams

---

authlib/oauth2/rfc8414/models.py

---
This allows to write server metadata file with insecure urls when developping locally, with the use of the `AUTHLIB_INSECURE_TRANSPORT` variable environment.

Use 'is_secure_transport' in rfc8414

---

authlib/integrations/base_client/async_app.py
authlib/integrations/base_client/remote_app.py

> on README.
The problem happens if server_metadata_url is used instead of manual passing access_token_url and token is not passed to request but via fetch_token callback registered in OAuth. When the token expires, and an OAuth resource is requested by invoking request/get/put, loader_server_metadata is skipped because token is not manually passed in (token=None). Thus, metadata is empty, OAuth2Auth.ensure_active_token() is unable to get token_endpoint, hence unable to refresh token, resulting in invalid token exception.
---

Remove token checking before load_server_metadata

---

authlib/integrations/django_client/integration.py
authlib/integrations/django_oauth2/signals.py

In Django 3.1 the purely documentational feature of sending in `providing_args` when creating a `Signal` was deprecated:
https://docs.djangoproject.com/en/3.1/releases/3.1/#id2
> The purely documentational providing_args argument for Signal is deprecated. If you rely on this argument as documentation, you can move the text to a code comment or docstring.
This removes the argument so that we don't get deprecation warnings.
The feature has been purely documentational since 1.8 so this shouldn't break anybody's code.

Remove deprecated and purely documentational argument providing_args in Django integrations

---

tests/core/test_oauth2/test_rfc8414.py
tests/core/test_oidc/test_discovery.py

Some tests throw unhelpful error messages when an expected exception is not thrown. This PR makes these tests report the correct error. It changes the use of the `self.assertRaises` context manager to be aligned with its [documented usage](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaises) (namely, using `cm` outside of the `with`-statement).
**Previously:**
`AttributeError: '_AssertRaisesContext' object has no attribute 'exception'`
**Now:**
`AssertionError: ValueError not raised`
---

Improve error reporting in tests

---

authlib/oidc/core/claims.py

according to spec 'auth_time' is JSON NUMBER which can be decimal
fixe #309
> on README.
---

Fix claims.py to support decimal values of `auth_time` claim

---

authlib/oauth2/rfc6750/token.py

The `expires_in` column already defaults to `0` and the `is_expired` method assumes a token with a falsy `expires_in` is never expired. The only thing this PR changes is not sending a misleading `expires_in: 0` (which sounds more like a token that immediately expired!) in this case.
---

Improve support for non-expiring oauth tokens

---

authlib/integrations/base_client/async_app.py
authlib/integrations/base_client/async_openid.py
authlib/integrations/base_client/sync_app.py
authlib/integrations/base_client/sync_openid.py
authlib/integrations/httpx_client/assertion_client.py
authlib/integrations/httpx_client/oauth2_client.py
authlib/oauth2/client.py
authlib/oauth2/rfc7521/client.py
authlib/oauth2/rfc7662/token_validator.py
docs/client/flask.rst
docs/client/frameworks.rst
docs/specs/rfc7662.rst

It is better to raise an exception due to an HTTP error status rather
than an error like the following which may be received due to a 502 Bad
Gateway which returns HTML content, for example.
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
---

Use resp.raise_for_status() before using resp.json().

---

authlib/oauth2/auth.py

Don't use urlsafe base64 encoding for client_secret_basic authorization headers because it doesn't play well with extraction of the authorization of certain client_secrets. 
Should fix #187
> on README.
---

Fix issue with long client secrets

---

authlib/integrations/httpx_client/oauth1_client.py
authlib/integrations/httpx_client/oauth2_client.py

---
---
Authlib raises deprecation warnings when used with the latest version of httpx.
This is because authlib uses the `Request(data="foo", ...)` syntax for string content, which is [deprecated](https://github.com/encode/httpx/pull/1573) as of httpx 0.18.0 (April 2021) in favour of `Request(content="foo", ...)` [introduced](https://github.com/encode/httpx/blob/master/CHANGELOG.md#0150-september-22nd-2020) in httpx 0.15.0 (September 2020).
This PR updates authlib to use the new syntax when the content is a string. (When the content is a dict, we still use `data=`.)

Use Request(content=...) for string content in httpx

---

authlib/oauth2/client.py

A fetch token request includes `state` value which is already consumed by`parse_authorization_code_response`. I validate a fetch token request very strictly, and don't want to get this field.
---
> on README.
---

Do not send state on fetch token

---

authlib/integrations/django_helpers.py
authlib/integrations/django_oauth1/resource_protector.py
authlib/integrations/django_oauth2/resource_protector.py

---
Django 4.0 removes the `request.get_raw_uri` method (https://code.djangoproject.com/ticket/32698). Switch to `request.build_absolute_uri` which should give the same result in regular cases.

Use request.build_absolute_uri instead of request.get_raw_uri

---

requirements-docs.txt

---
---
Currently authlib supports only httpx>=0.18.2. It fails with an error `ImportError: cannot import name 'USE_CLIENT_DEFAULT' from 'httpx' (/usr/local/lib/python3.9/site-packages/httpx/__init__.py)` when using with httpx 0.18.1.
- Pip dependency management does not work for authlib and httpx.
- authlib has started using `USE_CLIENT_DEFAULT` on https://github.com/lepture/authlib/commit/40276708374fcc7c0ee6b1ce4955dbe7db82f5ba
- httpx has added  `USE_CLIENT_DEFAULT` at `httpx 0.18.2` as …

Fix httpx dependency

---

authlib/integrations/httpx_client/oauth2_client.py
tests/starlette/test_httpx_client/test_async_oauth2_client.py

As title. Fixes #394. The anyio package is already a transitive dependency of httpx and starlette, so the only thing preventing usage of a trio backend with the async client integrations is the `asyncio.Event` being used to guard token refreshes. `anyio.Event` does not have a `reset` method, so I took the liberty of refactoring the critical section to use a `Lock`. The result is more readable, but I did have to update one test.
I'm not comfortable enough with your test suite to add a trio backend test, so I haven't tried to make any docs changes in this PR that announce trio compatibility as a new feature in the next release. Such testing may require anyio's …

Use anyio.Lock to support trio/anyio backends in httpx client integrations

---

authlib/integrations/sqla_oauth2/client_mixin.py
authlib/oauth2/rfc6749/models.py

Use `secrets.compare_digest` in the docstring of `ClientMixin.check_client_secret` and the`sqla_oauth2` `ClientMixin` implementation to prevent potential timing attacks.
Ref: Issue #431

Use constant time comparison for client_secret

---

authlib/oauth2/rfc7523/auth.py

This PR is a cherry-pick of https://github.com/lepture/authlib/pull/390, but into the master branch instead of v0.15
This feature is exactly what I need, but it's not in v1.0.0
---

allow to pass in alternative signing algoritm to RFC7523 authentication methods

---

authlib/integrations/django_client/apps.py
authlib/integrations/flask_client/apps.py
authlib/integrations/starlette_client/apps.py

---
---
This pull requests allows to put custom `claims_options` into the `StarletteOAuth2App`. This is needed for example in a multihomed Keycloak setup. Here, the users accesses Keycloak from a public URL (e.g. `https://keycloak.localhost` with a Reverse Proxy in front) which might not be reachable from the application (e.g. in a Docker Container). In that case, the program using `authlib` would access Keycloak directly using a private URL (e.g. `http://keycloak:8080`).
Here, the JWT `iss` would mismatch when retrieving the `user_info`, but the developer knows that it has two possible values: The public and the private URL. To suppress the validation error, the base function …

Allow passing claims_options in StarletteOAuth2App

---

docs/jose/jws.rst

EdDSA and ES256K were missing in the "full list of available algorithms".
---

Added EdDSA and ES256K

---

docs/client/oauth2.rst

The `token_endpoint` is a hard requirement for automatic token refreshes but I had to trace the call from `OAuth2Session` to `OAuth2Client` to find the expected value.
---

Document required configuration for automatic token refreshes

---

BACKERS.md
docs/client/oauth2.rst
docs/jose/jwt.rst

There are small typos in:
- BACKERS.md
- docs/client/oauth2.rst
- docs/jose/jwt.rst
Fixes:
- Should read `signature` rather than `signatrue`.
- Should read `authorization` rather than `authoirzation`.
- Should read `authentication` rather than `authencation`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

authlib/oauth2/rfc6749/authorization_server.py

In `generate_token` method we are getting default generator with: `func = self._token_generators.get('default')`.
---

Fix typo in register_token_generator docstring

---

authlib/oauth2/rfc6749/grants/authorization_code.py
tests/django/test_oauth2/test_authorization_code_grant.py
tests/flask/test_oauth2/test_authorization_code_grant.py

Currently, when validating params of `POST /token`, if the `code` or `redirect_uri` is invalid authlib returns an "invalid_request" error type.
[RFC 6749](https://www.rfc-editor.org/rfc/rfc6749.html#section-5.2) specifies that the `error` value will be `invalid_grant` in these cases:
>         invalid_grant
>               The provided authorization grant (e.g., authorization
>               code, resource owner credentials) or refresh token is
>               invalid, expired, revoked, does not match the redirection
>               URI used in the authorization request, or was issued to
>               another client.
---
Clients which depend on the current …

Use InvalidGrantError for invalid code, redirect_uri, user

---

authlib/oauth2/rfc6749/models.py

The previous version made tokens always look revoked. This change makes sure programmers (and IDEs) are properly notified about missing is_revoked implementation..
---

TokenMixin: actually raise a NotImplementedError

---

README.md
authlib/integrations/flask_helpers.py
authlib/integrations/sqla_oauth2/client_mixin.py
authlib/oauth2/rfc7592/endpoint.py
docs/changelog.rst
docs/specs/index.rst
docs/specs/rfc7592.rst
tests/flask/test_oauth2/test_client_configuration_endpoint.py

This PR fixes/implements the RFC7592 spec. It brings those changes
- The Flask integration keep the request data when the request type is `PUT`
- rfc7592/endpoint.py implements the RFC7592 specification
- The endpoint is tested by tests/flask/test_oauth2/test_client_configuration_endpoint.py
- rfc7592/endpoint.py has a 100% coverage
- The implementation is documented by docs/specs/rfc7592.rst
I read RFC7592 and did my best to implement this, but I am not 100% confident to have understood or implemented things right. I think a second pair of eyes might help. I tried to make unit tests as explicit and short as I could, and insert quotes from the spec to illustrate the tests.
The `extract_client_metadata` method has been copied from RFC7591 (and I removed the `software_statement` part). …

Fixed RFC7592 Dynamic Client Registration Management Protocol

---

docs/specs/rfc7636.rst

---
I've had to look through code to make sure, but it seems the CodeChallenge is only required when the client uses "none" authentication - which I understand as being a public client. This makes it explicit in the documentation.

docs: CodeChallenge(required=True) only applies to public clients

---

authlib/integrations/requests_client/oauth2_session.py
tests/clients/test_requests/test_oauth2_session.py

---
This is related to #451 - It resolves the issue that it's not possible to send a timeout when fetching server meta data or jwk keys. 
This fix uses a default timeout on every request, when timeout is provided to the `OAuth2Session`. 
If you have a different way you'd prefer to propagate timeout to the request please let me know, would be happy to amend accordingly.

Add support for default timeout in OAuth2Session

---

authlib/integrations/sqla_oauth2/client_mixin.py
docs/changelog.rst
docs/django/2/authorization-server.rst
tests/django/test_oauth2/models.py

I just noticed that `has_client_secret` is unused.
---

Removed `has_client_secret` method.

---

authlib/integrations/django_oauth2/resource_protector.py
authlib/integrations/flask_oauth2/resource_protector.py
authlib/integrations/sqla_oauth2/functions.py
docs/changelog.rst

This removes unused methods definition and documentation.
---

Removed `request_invalid` and `token_revoked` methods

---

authlib/jose/rfc7515/jws.py
tests/jose/test_jws.py

Previously the code checked if the payload value was True when converted to bool by the if statement, but that conflates None (i.e., no payload field in the JSON serialization) and the empty string (a specific payload), because both are False when converted to bool.  The proper check (as verified by the added test case) is to check if the payload is None.
- [ X ] Bugfix
---
- [ X ] You consent that the copyright of your pull request source code belongs to Authlib's author.

jws: correctly handle empty payload with JSON serialization

---

authlib/oauth2/rfc7591/endpoint.py
docs/changelog.rst
tests/flask/test_oauth2/test_client_registration_endpoint.py

The [RFC7591 dynamic client registration](https://www.rfc-editor.org/rfc/rfc7591.html#section-2) indicates default values for `response_types` and `grant_types`:
- If omitted, the default is that the client will use only the "code" response type.
- If omitted, the default behavior is that the client will use only the "authorization_code" Grant Type.
This is a better attempt than #509  
---

RFC7591: Use default values for 'response_types' and 'grant_types'

---

authlib/integrations/starlette_client/apps.py

Starlette `0.26.0` changed the return value of `url_for()` from `str` to `URL`; see https://github.com/encode/starlette/pull/1385 for context.
Passing a `redirect_uri` to `authorize_redirect` causes a `TypeError: cannot convert 'URL' object to bytes` exception to be raised if the URL has been generated via `url_for()`. This fix detects an instance of `URL` and casts it to a string, thus allowing authentication to proceed and generally making people happy.
---

Starlette v0.26.0 support and authorize_redirect fix

---

authlib/oauth2/rfc6749/parameters.py
tests/core/test_oauth2/test_rfc6749_misc.py

There are use cases where you want to pass `0` to `authorize_redirect`, for example Auth0 allows you to force login again by passing `max_age=0`, as described [here](https://auth0.com/docs/authenticate/login/max-age-reauthentication).
The current code for `prepare_grant_uri` filters out such parameters. This PR changes that to explicitly filter out `None` instead.
Debatable? Technically a breaking change if someone was passing a non-`None` falsey value to `authorize_redirect()` previously.
---

Allow falsey but non-None grant uri params

---

authlib/oauth2/rfc6749/authorization_server.py

Restore behaviour in create_authorization_response call which previously accepted a OAuth2Request object as-is

---

authlib/jose/rfc7519/claims.py
tests/jose/test_jwt.py

564 include leeway in validate_iat() to reject tokens that are 'issued in the future'

---

tox.ini

This allows to run tox with parameters for pytest. For instance `tox -e py311-flask -- tests/flask/test_oauth2/test_oauth2_server.py` will only run that test file.
If no argument is passed, the default `TESTPATH` is still used.

 use {posargs} tox parameter to customize pytest runs

---

tests/clients/test_django/settings.py
tests/django/settings.py

django tests use a inmemory sqlite database. This *should* be more performant but I doubt anyone will ever notice. However this avoids to create a `example.sqlite` file that git complains is untracked after running tox.

use in-memory sqlite database with django tests

---

tests/requirements-base.txt
tests/requirements-clients.txt

This prevents this warnings on some tox test environments:
```
.tox/py311-django/lib/python3.11/site-packages/_pytest/config/__init__.py:1373
/home/eloi/dev/authlib/.tox/py311-django/lib/python3.11/site-packages/_pytest/config/__init__.py:1373: PytestConfigWarning: Unknown config option: asyncio_mode
self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")
```
These warnings appears because this configuration is shared across all the tox environments:
https://github.com/lepture/authlib/blob/eaa51a8d65f21eff98ed0eb1b86b07801d68c98d/tox.ini#L27-L28

tests: move pytest-asyncio dependency in tests/requirements-base.txt

---

authlib/integrations/flask_oauth2/resource_protector.py
authlib/oauth2/rfc6749/grants/authorization_code.py
authlib/oauth2/rfc6749/grants/refresh_token.py
authlib/oauth2/rfc8628/device_code.py
tests/flask/test_oauth1/oauth1_server.py
tests/flask/test_oauth2/models.py
tests/flask/test_oauth2/oauth2_server.py
tests/flask/test_oauth2/test_device_code_grant.py
tests/flask/test_oauth2/test_introspection_endpoint.py
tests/flask/test_oauth2/test_refresh_token.py

This prevents these warnings to pop when running the unit tests:
```
LegacyAPIWarning: The Query.get() method is considered legacy as of the 1.x series of SQLAlchemy and becomes a legacy construct in 2.0. The method is now available as Session.get() (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
grant_user = User.query.get(int(user_id))
```
Also, the documentation use more *framework-generic* examples (`User.query.get` becomes `User.get`)

remove SQLAlchemy LegacyAPIWarning from unit tests

---

authlib/oauth2/client.py

When the `OAuth2Client` is not constructed explicitly with `grant_type='client_credentials'`, fetching the initial token works (due to the auto-detection of `client_credentials` in `_guess_grant_type`) but it then fails to auto-refresh the token (due to the check [here](https://github.com/lepture/authlib/blob/70a6bfa92aa1007515465a7af1a60a4518abe699/authlib/oauth2/client.py#L264)).
---

Auto refresh token for detected client_credentials grant type

---

authlib/common/errors.py
authlib/oauth2/rfc6749/authorization_server.py

I am currently tackling #427 and I realize it would be easier for me if one could register several endpoints of a kind. For instance one `JWTAccessTokenIntrospectionEndpoint` that would read the introspection data from the JWT access token, and a regular `IntrospectionEndpoint` for the other kind of tokens.
With this patch, if `JWTAccessTokenIntrospectionEndpoint` would meet a plain-text access token, it would raise a `ContinueIteration` exception and pass to the `IntrospectionEndpoint`. Same if the token_hint is a refresh token for instance (RFC9068 is only about access tokens).
This would also help for the revokation endpoint.
What do you think?

register several endpoints of a kind

---

BACKERS.md
README.md
authlib/integrations/django_oauth2/resource_protector.py
authlib/integrations/flask_oauth2/resource_protector.py
authlib/jose/errors.py
authlib/jose/rfc7519/jwt.py
authlib/oauth2/rfc6749/authorization_server.py
authlib/oauth2/rfc6749/resource_protector.py
authlib/oauth2/rfc7009/revocation.py
authlib/oauth2/rfc7662/introspection.py
authlib/oauth2/rfc9068/__init__.py
authlib/oauth2/rfc9068/claims.py
authlib/oauth2/rfc9068/introspection.py
authlib/oauth2/rfc9068/revocation.py
authlib/oauth2/rfc9068/token.py
authlib/oauth2/rfc9068/token_validator.py
docs/community/authors.rst
docs/specs/index.rst
docs/specs/rfc9068.rst
tests/flask/test_oauth2/test_jwt_access_token.py

This PR implements RFC9068 and fixes #427.
It implements:
- a token generator that builds JWT access tokens
- an introspection endpoint that introspects JWT access tokens
- a resource protector that validate authorizations against a JWT access token
- a revocation endpoint that refuses to revoke JWT access tokens
Everything is documented, and coverage is almost 100%, except on one part I will directly comment on the code.
I have left some comments for thing to be implemented with #524
Some notes about the implementation:
- resource protectors can take other arguments than `scope`, since RFC9068 introduces the `groups`, `entitlements` and `roles` claims to validate accesses
- `register_endpoint` can take objects, and not just classes
- I have not used joserfc yet. I thought it would be …

RFC9068 implementation

---

authlib/oauth2/auth.py

Added url encoding of client_id and client_secret in encode_client_secret_basic per RFC 6749:
https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1
This fixes the unsupported situation where there is a colon character in the client_id or in the client_secret.
> on README.
---

Fix encode_client_secret_basic to match RFC 6749

---

authlib/oauth2/rfc9068/token_validator.py

The `scope` claim is optional in RFC9068. This PR fixes the current behaviour which is that it is mandatory by authlib.
---

Fix error when RFC9068 JWS has no scope field

---

authlib/integrations/flask_oauth2/errors.py

Resolves deprecation warning:
```
.venv/lib/python3.11/site-packages/authlib/integrations/flask_oauth2/errors.py:4: DeprecationWarning: The '__version__' attribute is deprecated and will be removed in Werkzeug 3.1. Use feature detection or 'importlib.metadata.version("werkzeug")' instead.
_version = werkzeug.__version__.split('.')[0]
```
> on README.
---

 Get werkzeug version using importlib

---

authlib/oauth2/client.py

Make `client.refresh_token()` and `client.ensure_active_token()` work without needing to supply any parameters.
`client` may already have the necessary token endpoint or token, so caller should not be required to provide them.
---

Make token refresh more user friendly

---

authlib/integrations/flask_oauth2/errors.py

fixing https://github.com/lepture/authlib/issues/617
---

fix: AttributeError: module 'importlib' has no attribute 'metadata'

---

authlib/oauth2/rfc7636/challenge.py
tests/flask/test_oauth2/test_code_challenge.py

[Section 4.2 of RFC 7636](https://datatracker.ietf.org/doc/html/rfc7636#section-4.2) mentions the ABNF form to which the code challenge should adhere. authlib currently accepts any string in code_challenge without validating if it matches the format specified in the RFC. Fix the same and also update relevant tests.
---

rfc7636: validate code challenge format

---

authlib/oauth2/rfc7592/endpoint.py
tests/flask/test_oauth2/test_client_configuration_endpoint.py

---
---
While implementing [RFC7592 endpoint](https://github.com/lepture/authlib/blob/master/authlib/oauth2/rfc7592/endpoint.py) in my code base, I noticed a crash could occur when updating the client if `grant_types` or `response_types` were not provided:
```
File "/Users/fvoron/Development/polar/server/.venv/lib/python3.12/site-packages/authlib/oauth2/rfc7592/endpoint.py", line 147, in _validate_grant_types
return grant_types_supported.issuperset(set(value))
^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```
In RFC7591 endpoint, there is a fail-safe fallback to avoid this:
https://github.com/lepture/authlib/blob/5ac468051098d544dd5bfad24f692ec1a6bc7ec1/authlib/oauth2/rfc7591/endpoint.py#L110-L114 …

RFC7592: set default values for `grant_types` and `response_types` when updating client

---

authlib/oauth2/rfc6749/wrappers.py

Fix: fix token expiration check for proactive refreshing

---

authlib/integrations/flask_client/apps.py

> on README.
---
---
Instead of having the library users keeping track of which requests.args that are needed, change the behavior to not crash if variables requirements are not met. 
Example code before change:
```
authorize = Blueprint('authorize', __name__)
@authorize.route('/<client_name>')
def oauth(client_name):
""" Verify oauth """
args = request.args
if None in (args.get("code"), args.get("state")):
abort(500)
client = _oauth.create_client(client_name)
if not client:
abort(404)
token = client.authorize_access_token()
```
Example code after change:
Now the correct raise will occur which we can check for as expected:
```
from …
```

Make sure 'code' returns None instead of crashing if key is missing.

---

authlib/oauth2/rfc7009/revocation.py
tests/flask/test_oauth2/test_revocation_endpoint.py

[Section 2 of RFC 7009](https://datatracker.ietf.org/doc/html/rfc7009#section-2) says:
"The authorization server first validates the client credentials (in
case of a confidential client) and then verifies whether the token
was issued to the client making the revocation request.  If this
validation fails, the request is refused and the client is informed
of the error by the authorization server as described below."
Accordingly, update the code to return an invalid_grant error if the token being revoked does not belong to client credentials supplied.
---

rfc7009: return error if client validation fails

---

authlib/integrations/django_oauth2/requests.py
authlib/integrations/flask_oauth2/requests.py
authlib/oauth2/rfc6749/authorization_server.py
authlib/oauth2/rfc6749/grants/base.py
authlib/oauth2/rfc6749/requests.py
authlib/oauth2/rfc7636/challenge.py
tests/django/test_oauth2/test_authorization_code_grant.py
tests/flask/test_oauth2/test_authorization_code_grant.py

[Section 3.1 of the RFC6749](https://datatracker.ietf.org/doc/html/rfc6749#section-3.1) says "Request and response parameters MUST NOT be included more than once."
Add a method to the OAuth2Request object to obtain all the values for the keys in form + args data as a list. This helps detects repetition of request parameters. Also, add a django and flask test for the same.
Possible breaking change for applications because clients that were repeating parameters in the request will now get an InvalidRequest error instead of successful authorization.
I don't see a reason why any client …

rfc6749: ensure request parameters are not included more than once in authorization endpoint

---

authlib/integrations/httpx_client/oauth2_client.py
authlib/integrations/requests_client/assertion_session.py
authlib/integrations/requests_client/oauth2_session.py
authlib/oauth2/client.py
authlib/oauth2/rfc7521/client.py
docs/client/oauth2.rst
tests/clients/test_requests/test_oauth2_session.py

Issue #567 introduced a "leeway" parameter for proactive token refreshing. Expose this parameter in clients (e.g., the `requests` client) to allow configuring it by the library's users.
---

Expose leeway in clients

---

authlib/integrations/starlette_client/integration.py

Fix https://github.com/lepture/authlib/issues/622.
See https://github.com/lepture/authlib/issues/622#issuecomment-2049294579 for more context about the  proposed solution. The PR deletes old states from the cookie to avoid reaching the 4kb limit.
cc @lepture @frozturk

Fix ever-growing session cookie (starlette integration)

---

authlib/integrations/starlette_client/integration.py

---
---
Fixes issue where state data for OAuth could be set on an incorrect session key due to overwriting the key value when removing old session state data.

Fix: use unique variable name when clearing old state data

---

authlib/integrations/base_client/sync_app.py

fix: Fix list of scopes in app integrations

---

.github/workflows/pypi.yml

update upload-artifact and download-artifact GHA actions

---

.github/workflows/python.yml
tests/flask/test_oauth2/test_jwt_access_token.py
tox.ini

Adds Python 3.13 and removes Python 3.8 (EOL) from test runs. Fixes #679.
> on README.
---

Support Python 3.13

---

authlib/oidc/core/grants/util.py
tests/flask/test_oauth2/test_openid_code_grant.py

---
---
OpenID Connect specification states the following about the `prompt=login` parameter:
> The Authorization Server SHOULD prompt the End-User for reauthentication. If it cannot reauthenticate the End-User, it MUST return an error, typically login_required.
Ref: https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest
In the current implementation, if `end_user` is present, the `login` prompt is ignored and set to `None`. We should instead keep this prompt so the end-developer can force a re-authentication of the user.

fix: OIDC "login" prompt should be "login" even if user authenticated

---

docs/client/flask.rst

> DO NOT SEND ANY SECURITY FIX HERE. Please read the "Security Reporting" section
> on README.
---
The Flask OAuth Client documentation excludes important information about creating a `cache` instance for `OAuth` initialization.
Under FlaskClient `framework_integration.py` source code, 
```python
def clear_state_data(self, session, state):
key = f'_state_{self.name}_{state}'
if self.cache:
self.cache.delete(key)   # Calls the delete method on the cache object
else:
...
```
You are required to have a `delete` method for the `cache` object else you get an `AttributeError` like this `AttributeError("'Cache' object has no attribute 'delete'")`.
This PR updates the documentation to inform users about the need to have a …

Updated notes on using a ``cache`` instance when initializing ``OAuth``.

---

authlib/oauth2/client.py

When token introspection was introduced in 6f5d19a, using the code that previously only handled token revocation, the new `_handle_token_hint` method that does the work for both `introspect_token` and `revoke_token` kept using
`self.revocation_endpoint_auth_method` unconditionally if no `auth` was passed in with the introspect or revoke request. This seems to be wrong, introspecting a token should use the `token_endpoint_auth_method`.
This leaves the fallback to `revocation_endpoint_auth_method` in `_handle_token_hint` because adjusting its signature to make `auth` compulsory would be awkward, but it's not expected ever to be used.
---

OAuth2Client: use correct auth method for token introspection

---

authlib/jose/rfc7518/oct_key.py

When generating an oct key the entropy for the key material was only around 0.75 of the entropy requested by the key size. The reason for this was the limited alphabet `generate_token` uses with less than 6 bits per character instead of 8 bits
---

fix: Use full entropy from specified oct key size

---

authlib/oauth2/rfc9207/parameter.py
docs/changelog.rst

the URI was duplicated and appended to itself

fix RFC9207 iss parameter

---

.gitignore
authlib/integrations/base_client/async_openid.py
authlib/integrations/base_client/sync_openid.py
authlib/integrations/django_client/apps.py
authlib/integrations/flask_client/apps.py
authlib/integrations/starlette_client/apps.py
docs/changelog.rst

By passing a `claims_cls` parameter, developers can use their own claims validator. This will fix #725.

fix(client): add claims_cls parameter for parse_id_token, #725

---

authlib/jose/errors.py
authlib/oauth2/base.py
authlib/oauth2/rfc6749/authorization_server.py
authlib/oauth2/rfc6749/errors.py
authlib/oauth2/rfc6749/grants/authorization_code.py
authlib/oauth2/rfc6749/grants/base.py
authlib/oauth2/rfc6749/grants/client_credentials.py
authlib/oauth2/rfc6749/grants/implicit.py
authlib/oauth2/rfc6749/grants/refresh_token.py
authlib/oauth2/rfc6749/grants/resource_owner_password_credentials.py
authlib/oauth2/rfc7523/assertion.py
authlib/oauth2/rfc7523/jwt_bearer.py
authlib/oauth2/rfc7636/challenge.py
authlib/oauth2/rfc8628/device_code.py
authlib/oidc/core/grants/hybrid.py
authlib/oidc/core/grants/implicit.py
authlib/oidc/core/grants/util.py
docs/changelog.rst
tests/flask/test_oauth2/test_authorization_code_grant.py

[RFC7649 §4.1.2.1](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2.1) indicates that `error_description` have a restricted set of allowed characters, excluding the double-quote symbol `"`.
This PR replaces double quote usage in error description by simple quotes, and add a check for forbidden characters when emitting a OAuth2Error.
Fixes #720

Fix invalid characters in 'error_description'

---

authlib/oidc/discovery/models.py
tests/core/test_oidc/test_discovery.py

oidc-discovery indicates that 'Servers SHOULD support none and RS256.' but RFC2119 indicates that 'SHOULD' is synonym of 'RECOMMENDED' and not of 'REQUIRED'.
This PR makes 'none' and 'RS256' values optional for `request_object_signing_alg_values_supported`.
fixes #731
> on README.
---

Allow `request_object_signing_alg_values_supported` to not contain 'none' and 'RS256'

---

authlib/common/urls.py
authlib/oauth2/rfc7591/claims.py
docs/changelog.rst
tests/flask/test_oauth2/test_client_registration_endpoint.py

This PR prevents registration of clients with redirect_uris containing fragments.
Fixes #714
---

Forbid URL fragments in redirect_uris

---

authlib/oauth2/rfc9207/parameter.py
docs/changelog.rst

Fix an issue when rfc9207 is enabled and the authorization response is not a 302

---

docs/flask/2/authorization-server.rst

This PR adds a little example of error management with the Flask integration. As [RFC6749 §4.1.2.1](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2.1) indicates, some errors are expected to be included in the client_uri redirection query string, and some are intended to be displayed to the end-user. I had a hard time understanding the whole error management process, and how to return the correct thing (302 or 400), but in the end `handle_error_response` auto-magically handle errors.
I guess in the end this is how it is supposed to be used, can you confirm this @lepture?

Update Flask OAuth2 example to show error management

---

authlib/oauth2/rfc6749/models.py
docs/django/2/authorization-server.rst

The method is deprecated since version 1.0.0 that have been released in 2022.

Remove deprecated 'check_token_endpoint_auth_method' method

---

authlib/integrations/sqla_oauth2/tokens_mixins.py
authlib/oidc/core/grants/code.py
authlib/oidc/core/grants/util.py
authlib/oidc/core/models.py
docs/changelog.rst
tests/flask/test_oauth2/models.py
tests/flask/test_oauth2/test_openid_code_grant.py

Adds a way to set the `acr` and `amr` claims in `id_token` in the same fashion that `auth_time`.
Fixes #734

Support for 'acr' and 'amr' claims in id_token

---

authlib/oauth2/rfc6749/authenticate_client.py
authlib/oauth2/rfc6749/authorization_server.py
authlib/oauth2/rfc6749/grants/authorization_code.py
authlib/oauth2/rfc6749/grants/base.py
authlib/oauth2/rfc6749/grants/implicit.py
authlib/oidc/core/grants/implicit.py
docs/changelog.rst
tests/flask/test_oauth2/test_openid_code_grant.py

This is a refactoring that catches all errors from the authorization endpoint and dynamically add a `state` parameter instead of manually setting it on all errors.
This ensures the state parameter will always be present, and developers don't have to explicitly set (or forget) it.
Fixes #525

Fix missing 'state' param in authorization error responses

---

authlib/oauth2/rfc7591/claims.py
docs/changelog.rst
tests/flask/test_oauth2/test_client_registration_endpoint.py

As per RFC6749 §3.1.1:
Extension response types MAY contain a space-delimited (%x20) list of
values, where the order of values does not matter (e.g., response
type "a b" is the same as "b a").
Fix #760

Fix `response_types` order unwanted strictness during dynamic client registration

---

authlib/oauth2/rfc6749/authorization_server.py
authlib/oauth2/rfc6749/errors.py
tests/flask/test_oauth2/test_openid_hybrid_grant.py

As indicated by [RFC6749 §4.1.2.1](https://www.rfc-editor.org/rfc/rfc6749.html#section-4.1.2.1), authorization endpoint errors except client and redirect_uri errors result in a redirection:
```
If the resource owner denies the access request or if the request
fails for reasons other than a missing or invalid redirection URI,
the authorization server informs the client by adding the following
parameters to the query component of the redirection URI using the
"application/x-www-form-urlencoded" format
```

`unsupported_response_type` errors are redirected

---

tests/jose/test_chacha20.py

Skip `xc20p` algorithm unit tests when unavailable in cryptodome

---

authlib/integrations/django_oauth2/requests.py
authlib/integrations/flask_oauth2/requests.py
authlib/oauth2/rfc6749/requests.py
docs/changelog.rst

This restores and deprecate the `OAuth2Request` parameter that have been removed with 1.6.0.
---
---

Temporarily restore OAuth2Request body parameter

---

authlib/integrations/sqla_oauth2/client_mixin.py
authlib/oidc/core/grants/code.py
authlib/oidc/core/grants/implicit.py
docs/changelog.rst
tests/flask/test_oauth2/test_openid_code_grant.py
tests/flask/test_oauth2/test_openid_implict_grant.py

The behavior to find the `alg` with which the id_token is signed is:
- use `alg` is set in `get_jwt_config` if defined
- else use `client.id_token_signed_response_alg` if defined
- else use the default `RS256`
I think `client.id_token_signed_response_alg` should take precedence over `get_jwt_config`, but that would be a breaking change. I will open another ticket for that, this could target v1.8.
Working on this part of the code made me realize that he `get_jwt_config` might be a little outdated. We would probably want use `get_server_jwks` instead here, instead of manually passing a key. What do you think?
fixes #755 
**Checklist**
---

Sign OIDC id_token  according to id_token_signed_response_alg client metadata

---

authlib/oauth2/rfc6749/authorization_server.py
docs/changelog.rst
tests/django/test_oauth2/oauth2_server.py
tests/django/test_oauth2/test_authorization_code_grant.py

There was an issue with InsecureTransportError being raised while the request has not fully been initialized by Django/Flask. Then the authorization server would try to catch the exception and enrich with request.payload.state, that don't exist because the request is not initialized.
The fix is to avoid enriching the 'state' parameter for exceptions raised during the request initialization, that for the moment can only be InsecureTransportError.
fixes #795 
**Checklist**
---

Fix `InsecureTransportError` raising

---

authlib/oauth2/rfc7591/endpoint.py
docs/changelog.rst

If the authentication token is a JWT containing data, such as the client_id to use, it should be available in the `generate_client_id` method. Thus this PR makes the `request` object available in the method.
Yes, but it is backward compatible until 1.8.
**Checklist**
---

Add a `request` param to RFC7591 `generate_client_info` and `generate_client_secret` methods
