authlib/client/apps/__init__.py
authlib/client/apps/google.py
tests/test_apps_client/test_apps_for_flask.py

Thsi PR add `google_fetch_user()` function for the built-in google client.
**The PR fulfills these requirements:**

add google_fetch_user function

---

authlib/client/flask/oauth.py

**The PR fulfills these requirements:**
If adding a **new feature**, the PR's description includes:

#5 fix passing individual key/value arguments to authorize_access_token

---

authlib/client/oauth2.py

Fix revoke_token in client

---

docs/specs/rfc7662.rst

register_endpoint was registering MyRevocationEndpoint, it has been changed to register MyIntrospectionEndpoint.
---

Updated documentation

---

authlib/client/client.py

Add patch http method to OAuthClient

---

authlib/common/security.py
authlib/specs/rfc6749/resource_protector.py

Add handling of tokens without spaces

---

.travis.yml
tox.ini

Added testing for python 3.7

---

authlib/flask/client/oauth.py

fix for GH-84

---

authlib/oauth2/rfc6749/authenticate_client.py
authlib/oauth2/rfc6749/grants/authorization_code.py
authlib/oauth2/rfc6749/grants/client_credentials.py
authlib/oauth2/rfc6749/grants/implicit.py
authlib/oauth2/rfc6749/grants/refresh_token.py
authlib/oauth2/rfc6749/grants/resource_owner_password_credentials.py
authlib/oauth2/rfc7523/client.py
authlib/oauth2/rfc7523/grant.py
authlib/oidc/core/grants/hybrid.py
authlib/oidc/core/grants/implicit.py

do not call format in logging statements

---

README.md
docs/flask/2/grants.rst

A couple of pronoun updates for the docs.

---

authlib/oauth1/client.py

Fill in error message variables.

---

docs/flask/2/openid-connect.rst

Details on UserInfo and OIDC Code flow #133

---

authlib/client/oauth_client.py

Changed `ro` to `or`
> on README.
---

Fixed a very minor typo in docs

---

authlib/oauth2/client.py

Fix small typo: supportted -> supported.

---

docs/client/oauth2.rst
docs/specs/rfc7636.rst

```
thise -> this
session.authorization_url(…) -> session.create_authorization_url
```
> on README.
---

doc: fix typos and method name

---

docs/jose/jwt.rst

Doc: fix variable name

---

docs/client/django.rst

docs/client/django: import OAuth from integrations

---

authlib/integrations/sqla_oauth2/client_mixin.py

This is PR regarding issue [#204](https://github.com/lepture/authlib/issues/204)
---

add empty string as client scope default value

---

docs/django/2/openid-connect.rst

Found few typos.
Documentation improvement.
---

Update Django OIDC docs

---

authlib/jose/__init__.py
authlib/jose/drafts/__init__.py
authlib/jose/drafts/_backends/__init__.py
authlib/jose/drafts/_backends/_jwe_enc_cryptography.py
authlib/jose/drafts/jwe_algorithms.py
tests/core/test_jose/test_jwe.py

> on README.
---
Hi, I was missing a ChaCha20-Poly1305 encoding algorithm so I added one myself.
however, I'm a novice at cryptography, any help appreciated. 
Thanks

Feature C20PEncAlgorithm

---

docs/specs/rfc7518.rst

Typo: "SHA-521" --> SHA-512 in RFC7518

---

authlib/integrations/httpx_client/oauth2_client.py
tests/py3/test_httpx_client/test_async_oauth2_client.py

#266 add test and fix for unintentional parallel token refreshes

---

docs/client/django.rst

Fix in the docs
I tried following the docs for my Django code, but saw that it needed additional paramters
---

Include correct parameters in django example

---

authlib/integrations/httpx_client/assertion_client.py

Make HTTPX AssertionClient work

---

authlib/integrations/httpx_client/oauth2_client.py
tests/starlette/test_httpx_client/test_async_oauth2_client.py
tests/starlette/test_httpx_client/test_oauth2_client.py

Implement OAuth2 for httpx streaming requests

---

authlib/integrations/flask_oauth2/errors.py

Modify _HTTPException to work with werkzeug 2.0.0

---

authlib/jose/rfc7519/claims.py
tests/core/test_jose/test_jwt.py

> on README.
Implements #349 
-  [x] You consent that the copyright of your pull request source code belongs to Authlib's author.

custom claims for JWT

---

authlib/integrations/starlette_client/integration.py

There is a case, when a session object is None, and the state manager in starlette integration becomes broken.
---

Add checking the session object for being not None

---

authlib/jose/rfc7518/jwe_algs.py

Drop extraneous print statement

---

authlib/jose/drafts/_jwe_algorithms.py
authlib/jose/errors.py
authlib/jose/rfc7515/jws.py
authlib/jose/rfc7516/jwe.py
authlib/jose/rfc7516/models.py
authlib/jose/rfc7518/jwe_algs.py
authlib/jose/util.py
tests/core/test_jose/test_jwe.py

- Added JSON serialization and multi-recipient support to JWE
---

Added JSON serialization and multi-recipient support to JWE

---

docs/client/django.rst

Fix some typos in django.rst

---

authlib/integrations/httpx_client/oauth2_client.py
authlib/integrations/httpx_client/utils.py

---
P.S. here's the according link for the newer httpx version changelog: [https://github.com/encode/httpx/blob/master/CHANGELOG.md#changed](url)

HTTPX 0.20: add .extensions attribute to a recreated request in auth_flow

---

docs/client/flask.rst
docs/client/frameworks.rst

Various documentation improvements

---

docs/flask/1/authorization-server.rst
docs/flask/2/authorization-server.rst
docs/flask/2/grants.rst
docs/flask/2/openid-connect.rst
docs/flask/2/resource-server.rst

Flask Oauth Providers documentation proofread

---

authlib/integrations/django_client/apps.py
authlib/integrations/flask_client/apps.py
authlib/integrations/starlette_client/apps.py

🐛 Clear state from session in OAuth2

---

docs/django/2/grants.rst

Consistently use AuthorizationCode model

---

authlib/integrations/requests_client/oauth2_session.py
authlib/oauth2/client.py
authlib/oauth2/rfc6749/parameters.py

fix #444: supply state to session and client

---

BACKERS.md
docs/changelog.rst
docs/flask/1/authorization-server.rst

that's all :)
- [x ] Other, please describe:
just some spelling mistakes
- [X ] No
---
- [ x] You consent that the copyright of your pull request source code belongs to Authlib's author.

fixed some spelling mistakes,

---

docs/specs/rfc7518.rst

Fix typo for algorithm name

---

authlib/integrations/httpx_client/oauth1_client.py

Signed-off-by: Cattī Crūdēlēs <17695588+wzy9607@users.noreply.github.com>
This pull request applies the same fix that #402 did for OAuth2Auth to OAuth1Auth.
---

Fix httpx_client.OAuth1Auth not respectng timeout

---

authlib/integrations/starlette_client/integration.py

Serialize cache value to JSON before trying to parse it as JSON

---

authlib/integrations/starlette_client/apps.py
docs/client/index.rst

Does:
- fix docstring in **Starlette** integration _source file_
- fix **Starlette** docs link in _web docs_
---

Fix some docs typos related to Starlette

---

docs/flask/2/openid-connect.rst

Fix typo in docs

---

.github/workflows/python.yml
setup.cfg
tox.ini

This simply adds tests for python 3.11
---

Python 3.11 support

---

setup.cfg

Use the produciton/stable [PyPI classifier](https://pypi.org/classifiers/), so people don't think this package is beta-quality software.
---

Classify as Stable on PyPI

---

authlib/integrations/httpx_client/assertion_client.py
authlib/integrations/httpx_client/oauth1_client.py
authlib/integrations/httpx_client/oauth2_client.py

Change httpx clients import style

---

authlib/oauth2/rfc7523/auth.py
tests/core/test_oauth2/test_rfc7523.py

> on README.
Fix for #515 with tests for RFC7523
---

515 RFC7523 apply headers while signing

---

authlib/jose/rfc7519/jwt.py

Fix typo in docstring

---

docs/client/flask.rst

Fix import within flask example

---

docs/client/fastapi.rst

The reference of fastapi doc has been changed. Update the path accrodingly.
---

Doc: Update the reference link of fastapi

---

.github/workflows/python.yml
docs/changelog.rst
setup.cfg
tox.ini

This adds unit tests and packaging classifiers for python 3.12

python 3.12 support

---

authlib/oauth2/rfc7523/token.py

fix https://github.com/lepture/authlib/issues/607

---

docs/specs/rfc7523.rst

- `authenticate_user` was referring to an undefined variable `sub`
- `resolve_client_key` had no return value

rfc7523 documentation improvements

---

docs/client/oauth1.rst

fix typo in oauth1.rst

---

docs/oauth/2/intro.rst

Hello team!
I'm implementing Authlib in an app I'm working on, thank you for your good work!
While reading the docs, I realized the name GitHub was missing a T, so I'm submitting this fix for your approval.
Thank you and have a great day!
---

docs: typo fix

---

authlib/integrations/base_client/sync_openid.py

This approach allows implementors to define custom key selection strategy without need to override the entire parse_id_token method.
> on README.
---

Extract load_key construction to separate method

---

docs/jose/jwt.rst

docs: fix typo

---

docs/client/flask.rst

Fixed typos and grammatical errors in the flask_client docs.

---

authlib/oauth2/rfc6749/authenticate_client.py
authlib/oauth2/rfc6749/grants/authorization_code.py
authlib/oauth2/rfc6749/grants/client_credentials.py
authlib/oauth2/rfc6749/grants/refresh_token.py
authlib/oauth2/rfc6749/grants/resource_owner_password_credentials.py
authlib/oauth2/rfc7523/client.py
authlib/oauth2/rfc7523/jwt_bearer.py
authlib/oauth2/rfc7592/endpoint.py
authlib/oauth2/rfc8628/device_code.py
docs/changelog.rst

As discussed on Discord, here are additional `descriptions` to common exceptions raised by Authlib.

add descriptions to InvalidClientError and UnauthorizedClientError

---

pyproject.toml

This istalls `tox-uv` and `pre-commit-uv` in the development environment. tox-uv greatly speeds up the environment build, that is very appreciable when developing.
---

Use tox-uv and pre-commit-uv

---

docs/specs/rfc7591.rst

Example for RFC7591 generate_client_registration_info

---

.pre-commit-config.yaml
authlib/oauth2/rfc7592/endpoint.py
authlib/oauth2/rfc9068/token.py
docs/changelog.rst
docs/client/oauth1.rst
docs/client/oauth2.rst
docs/specs/rfc9068.rst

This adds a pre-commit tool that checks for spelling errors in the source code and the documentation.

Add codespell pre-commit

---

authlib/oauth2/rfc6749/models.py
authlib/oidc/core/__init__.py
authlib/oidc/core/claims.py
authlib/oidc/core/userinfo.py
docs/changelog.rst
docs/django/2/openid-connect.rst
docs/flask/2/openid-connect.rst
docs/specs/oidc.rst
tests/flask/test_oauth2/models.py
tests/flask/test_oauth2/test_userinfo.py

OIDC userinfo endpoint support

---

authlib/integrations/base_client/__init__.py
authlib/integrations/base_client/errors.py
authlib/integrations/django_client/apps.py
authlib/integrations/flask_client/apps.py
authlib/integrations/starlette_client/apps.py
authlib/oauth2/client.py
authlib/oauth2/rfc6749/parameters.py
tests/clients/test_flask/test_oauth_client.py

According to https://github.com/authlib/authlib/issues/793, our previous fix doesn't work well. This is another fix.
---

fix(client): raise MissingCodeException when code parameter is missing

---

.github/workflows/python.yml
pyproject.toml

Run GHA unit tests with uv

---

authlib/jose/rfc7515/models.py
authlib/jose/rfc7516/models.py
tests/jose/test_jws.py

Fixes https://github.com/authlib/authlib/issues/337
**Checklist**
---

fix(jose): prevent public/unprotected header overwriting protected header

---

pyproject.toml

Fixes missing long description in package metadata and PyPI page
**Checklist**
- ~You wrote unit test to demonstrate the bug you are fixing, or to stress the feature you are bringing.~ *N/A*
- ~You reached 100% of code coverage on the code you edited, without abusive use of `pragma: no cover`~ *N/A*
- ~If this PR is about a new feature, or a behavior change, you have updated the documentation accordingly.~ *N/A*
---

Specify README.md as project long description
